dependencies: 
  pre: 
    - "echo y | android update sdk --no-ui --all --filter build-tools-23.0.3,android-23,extra-google-m2repository,extra-google-google_play_services,extra-android-support,extra-android-m2repository"
    - "chmod +x gradlew"
general: 
  artifacts: 
    - app/build/outputs/apk/app-release.apk
  branches: 
    only: 
      - master
      - dev
#     - /feature-.*/ # or regexes
test: 
  post: 
    - "./gradlew assembleRelease"